import { ServiceCategory, Leader, TranslationSchema, Language } from './types';

export const IMAGE_PROMPT_SUFFIX = "photorealistic, 8k, unreal engine 5 render, cinematic lighting, futuristic corporate, minimalist, Huly style, dark mode, Nano Banana Pro style";

export const TRANSLATIONS: Record<Language, TranslationSchema> = {
  en: {
    nav: { philosophy: "Philosophy", systems: "Systems", leadership: "Leadership", deploy: "Deploy", home: "Home" },
    hero: {
      tagline: "Sovereign Intelligence",
      headline: "Autonomous Infrastructure.\nGlobal Authority.",
      subheadline: "We engineer high-margin automated ecosystems. Bridging Western Enterprise Demand with Milanese Design Precision. The future is autonomous.",
      cta: "Deploy Infrastructure",
      caseStudies: "View Case Studies",
      stat1Label: "Total Automation",
      stat1Value: "99.9%",
      stat2Label: "Cost Reduction",
      stat2Value: "$4.2M/yr",
      loc1: "GLOBAL HQ",
      loc2: "INNOVATION HUB",
    },
    philosophy: {
      title: "The Sovereign Model",
      subtitle: "A dual-node architecture designed for speed, security, and absolute scale.",
      card1Title: "Governance Core",
      card1Subtitle: "COMPLIANCE & RISK",
      card1Desc: "The foundation of our operation. We adhere to G20 Compliance standards, ACCA Financial Controls, and strict data sovereignty protocols. We provide the legal shield and enterprise assurance required by the Fortune 500.",
      card2Title: "Neural Foundry",
      card2Subtitle: "DEEP TECH EXECUTION",
      card2Desc: "The engine of creation. Home to our Agentic AI Swarms in Milan. We bypass bureaucratic slowdowns to prototype, deploy, and iterate on complex neural networks at unprecedented speeds.",
      processTitle: "Deployment Protocol",
      step1: "Audit & Architecture",
      step2: "Agentic Swarm Deployment",
      step3: "Autonomous Scale",
    },
    systems: {
      title: "The Solution Matrix",
      subtitle: "25 Specialized Systems. Organized for immediate impact.",
    },
    leadership: {
      title: "The Architects",
      subtitle: "The intersection of Strategic Governance and Neural Engineering.",
    },
    footer: {
      basedIn: "Operating Globally.",
      rights: "All Sovereign Rights Reserved.",
      request: "Request Access"
    },
    // Content Keys
    retail_name: "Cognitive Commerce",
    retail_desc: "Retail",
    r1_title: "Omni-Aware Sales Concierge",
    r1_desc: "Multi-modal AI answering complex queries 24/7.",
    r2_title: "Supply Chain Neural Network",
    r2_desc: "Predictive ML adjusting POs based on live trends.",
    r3_title: "Dynamic Profit Engine",
    r3_desc: "Real-time pricing elasticity for 50k SKUs.",
    r4_title: "Churn Defense Grid",
    r4_desc: "Predicting VIP churn and automating retention.",
    r5_title: "Visual Discovery",
    r5_desc: "Vector-based photo-to-inventory search.",
    
    real_estate_name: "PropTech Autonomy",
    real_estate_desc: "Real Estate",
    re1_title: "Lead-to-Close Autopilot",
    re1_desc: "AI Voice agent qualifying leads & booking viewings.",
    re2_title: "Predictive Valuation",
    re2_desc: "Black-box algo using 50+ data points for appraisal.",
    re3_title: "Asset Management OS",
    re3_desc: "Auto-dispatching contractors & handling renewals.",
    re4_title: "Generative Staging",
    re4_desc: "AI converting empty rooms to luxury suites instantly.",
    re5_title: "Yield Forecaster",
    re5_desc: "Airbnb vs Long-term rental ROI prediction.",
    
    b2b_name: "Agency Operating System",
    b2b_desc: "B2B",
    b1_title: "Shadow Development Foundry",
    b1_desc: "White-label SDLC (PM, QA, DevOps) for agencies.",
    b2_title: "Programmatic Content Core",
    b2_desc: "Generating 500+ SEO authority articles/month.",
    b3_title: "Ad Creative Factory",
    b3_desc: "GenAI creating/testing 100+ ad variations.",
    b4_title: "Cross-Channel Data Warehouse",
    b4_desc: "Unifying data into one C-Suite dashboard.",
    b5_title: "Sales Intelligence",
    b5_desc: "Monitoring funding signals to trigger outreach.",

    corporate_name: "Enterprise Neural Network",
    corporate_desc: "Corporate",
    c1_title: "Financial Reconciliation Fabric",
    c1_desc: "Multi-agent swarm matching Invoices/POs/Receipts.",
    c2_title: "Cognitive Legal Defense",
    c2_desc: "Private LLM reviewing Contracts for risk.",
    c3_title: "Knowledge Intelligence Hub",
    c3_desc: "Vector DB indexing all calls/slack/docs for recall.",
    c4_title: "Workflow Orchestration",
    c4_desc: "Autonomous employee onboarding (IT, Payroll).",
    c5_title: "Logistics Optimizer",
    c5_desc: "Dynamic fleet re-routing based on traffic/weather.",

    health_name: "Clinical Operations OS",
    health_desc: "Healthcare",
    h1_title: "Patient Reactivation",
    h1_desc: "Auto-booking dormant patients.",
    h2_title: "Insurance Adjudication",
    h2_desc: "RPA bot verifying eligibility instantly.",
    h3_title: "Post-Op Monitoring",
    h3_desc: "Voice agent checking on recovery.",
    h4_title: "Reputation Autopilot",
    h4_desc: "Sentiment-triggered review requests.",
    h5_title: "Zero-Wait Voice Command",
    h5_desc: "AI answering phones & integrating with EMR.",

    ali_role: "Strategic Director",
    ali_arch: "The Governance",
    ali_desc: "Capital, Risk, Compliance, and Global Structuring. Ensuring the financial fortress.",
    bilal_role: "Head of Engineering",
    bilal_arch: "The Engine",
    bilal_desc: "Agentic Architecture and the Expert Circle. Deep Tech Execution and Neural Design.",
  },
  ar: {
    nav: { philosophy: "الفلسفة", systems: "الأنظمة", leadership: "القيادة", deploy: "ابدأ الآن", home: "الرئيسية" },
    hero: {
      tagline: "ذكاء سيادي",
      headline: "بنية تحتية مستقلة.\nسلطة عالمية.",
      subheadline: "نحن نهندس أنظمة بيئية آلية عالية العائد. سد الفجوة بين طلب المؤسسات الغربية ودقة التصميم في ميلانو.",
      cta: "نشر البنية التحتية",
      caseStudies: "عرض دراسات الحالة",
      stat1Label: "أتمتة كاملة",
      stat1Value: "٩٩.٩٪",
      stat2Label: "تخفيض التكاليف",
      stat2Value: "$٤.٢ مليون/سنة",
      loc1: "المقر العالمي",
      loc2: "مركز الابتكار",
    },
    philosophy: {
      title: "النموذج السيادي",
      subtitle: "بنية مزدوجة مصممة للسرعة والأمان والنطاق المطلق.",
      card1Title: "نواة الحوكمة",
      card1Subtitle: "الامتثال والمخاطر",
      card1Desc: "أساس عملياتنا. نلتزم بمعايير امتثال G20 والضوابط المالية ACCA وبروتوكولات سيادة البيانات الصارمة.",
      card2Title: "المسبك العصبي",
      card2Subtitle: "تنفيذ التكنولوجيا العميقة",
      card2Desc: "محرك الإبداع. موطن أسراب الذكاء الاصطناعي لدينا في ميلانو. نتجاوز البيروقراطية لنشر الشبكات العصبية المعقدة بسرعة غير مسبوقة.",
      processTitle: "بروتوكول النشر",
      step1: "التدقيق والهندسة",
      step2: "نشر الأسراب الذكية",
      step3: "التوسع الذاتي",
    },
    systems: {
      title: "مصفوفة الحلول",
      subtitle: "٢٥ نظاماً متخصصاً. منظمة لتأثير فوري.",
    },
    leadership: {
      title: "المهندسون المعماريون",
      subtitle: "نقطة التقاء الحوكمة الاستراتيجية والهندسة العصبية.",
    },
    footer: {
      basedIn: "عمليات عالمية.",
      rights: "جميع الحقوق السيادية محفوظة.",
      request: "طلب الوصول"
    },
    retail_name: "التجارة المعرفية",
    retail_desc: "تجزئة",
    r1_title: "المساعد الذكي الشامل",
    r1_desc: "ذكاء اصطناعي متعدد الوسائط يجيب على الاستفسارات ٢٤/٧.",
    // Shortened for brevity in example, would be full translation
    r2_title: "شبكة التوريد العصبية",
    r2_desc: "تعلم آلي تنبؤي لتعديل الطلبات.",
    r3_title: "محرك الربح الديناميكي",
    r3_desc: "مرونة التسعير الفوري لـ ٥٠ ألف منتج.",
    r4_title: "شبكة الدفاع ضد الانسحاب",
    r4_desc: "توقع انسحاب العملاء وأتمتة الاحتفاظ بهم.",
    r5_title: "الاكتشاف البصري",
    r5_desc: "بحث المخزون بالصور.",
    real_estate_name: "أتمتة العقارات",
    real_estate_desc: "العقارات",
    re1_title: "طيار آلي للمبيعات",
    re1_desc: "وكيل صوتي لتأهيل العملاء وحجز المواعيد.",
    re2_title: "التقييم التنبؤي",
    re2_desc: "خوارزمية الصندوق الأسود للتقييم الفوري.",
    re3_title: "نظام إدارة الأصول",
    re3_desc: "توجيه المقاولين وتجديد العقود آلياً.",
    re4_title: "التجهيز التويدي",
    re4_desc: "تحويل الغرف الفارغة إلى أجنحة فاخرة.",
    re5_title: "توقعات العائد",
    re5_desc: "مقارنة عوائد الإيجار القصير والطويل.",
    b2b_name: "نظام تشغيل الوكالات",
    b2b_desc: "الشركات",
    b1_title: "مسبك التطوير الظلي",
    b1_desc: "تطوير برمجيات كامل للوكالات.",
    b2_title: "نواة المحتوى البرمجي",
    b2_desc: "توليد ٥٠٠+ مقال SEO شهرياً.",
    b3_title: "مصنع الإعلانات",
    b3_desc: "إنشاء واختبار ١٠٠+ إعلان.",
    b4_title: "مستودع البيانات الشامل",
    b4_desc: "توحيد البيانات في لوحة تحكم واحدة.",
    b5_title: "استخبارات المبيعات",
    b5_desc: "مراقبة إشارات التمويل.",
    corporate_name: "الشبكة العصبية للمؤسسات",
    corporate_desc: "المؤسسات",
    c1_title: "نسيج المطابقة المالية",
    c1_desc: "سرب ذكي لمطابقة الفواتير.",
    c2_title: "الدفاع القانوني المعرفي",
    c2_desc: "مراجعة العقود للمخاطر.",
    c3_title: "مركز استخبارات المعرفة",
    c3_desc: "فهرسة المكالمات والمستندات.",
    c4_title: "تنسيق سير العمل",
    c4_desc: "تأهيل الموظفين آلياً.",
    c5_title: "محسن اللوجستيات",
    c5_desc: "إعادة توجيه الأسطول ديناميكياً.",
    health_name: "نظام العمليات السريرية",
    health_desc: "الرعاية الصحية",
    h1_title: "تنشيط المرضى",
    h1_desc: "حجز تلقائي للمرضى الخاملين.",
    h2_title: "البت في التأمين",
    h2_desc: "بوت للتحقق من الأهلية فوراً.",
    h3_title: "مراقبة ما بعد الجراحة",
    h3_desc: "وكيل صوتي للاطمئنان على التعافي.",
    h4_title: "طيار السمعة الآلي",
    h4_desc: "طلبات تقييم بناءً على المشاعر.",
    h5_title: "أوامر صوتية فورية",
    h5_desc: "الرد على الهواتف والتكامل مع السجلات.",
    ali_role: "المدير الاستراتيجي",
    ali_arch: "الحوكمة",
    ali_desc: "رأس المال والمخاطر والامتثال والهيكلة العالمية.",
    bilal_role: "رئيس الهندسة",
    bilal_arch: "المحرك",
    bilal_desc: "الهندسة الوكيلية وتنفيذ التكنولوجيا العميقة.",
  },
  it: {
    nav: { philosophy: "Filosofia", systems: "Sistemi", leadership: "Leadership", deploy: "Inizia", home: "Home" },
    hero: {
      tagline: "Intelligenza Sovrana",
      headline: "Infrastruttura Autonoma.\nAutorità Globale.",
      subheadline: "Progettiamo ecosistemi automatizzati ad alto margine. Uniamo la domanda aziendale occidentale con la precisione del design di Milano.",
      cta: "Implementa Infrastruttura",
      caseStudies: "Vedi Casi Studio",
      stat1Label: "Automazione Totale",
      stat1Value: "99.9%",
      stat2Label: "Riduzione Costi",
      stat2Value: "€3.9M/anno",
      loc1: "SEDE GLOBALE",
      loc2: "HUB INNOVAZIONE",
    },
    philosophy: {
      title: "Il Modello Sovrano",
      subtitle: "Un'architettura a doppio nodo progettata per velocità, sicurezza e scala assoluta.",
      card1Title: "Nucleo di Governance",
      card1Subtitle: "CONFORMITÀ E RISCHIO",
      card1Desc: "Le fondamenta della nostra operazione. Aderiamo agli standard G20 e ai controlli finanziari ACCA. Forniamo lo scudo legale richiesto dalle Fortune 500.",
      card2Title: "Fonderia Neurale",
      card2Subtitle: "ESECUZIONE DEEP TECH",
      card2Desc: "Il motore della creazione. Sede dei nostri sciami di IA agentica a Milano. Aggiriamo i rallentamenti burocratici per distribuire reti neurali complesse.",
      processTitle: "Protocollo di Distribuzione",
      step1: "Audit & Architettura",
      step2: "Distribuzione Sciame",
      step3: "Scala Autonoma",
    },
    systems: {
      title: "La Matrice delle Soluzioni",
      subtitle: "25 Sistemi Specializzati. Organizzati per un impatto immediato.",
    },
    leadership: {
      title: "Gli Architetti",
      subtitle: "L'intersezione tra Governance Strategica e Ingegneria Neurale.",
    },
    footer: {
      basedIn: "Operiamo Globalmente.",
      rights: "Tutti i Diritti Sovrani Riservati.",
      request: "Richiedi Accesso"
    },
    // Fallback English for dynamic items in demo to save space, normally fully translated
    retail_name: "Commercio Cognitivo",
    retail_desc: "Retail",
    r1_title: "Concierge di Vendita Omni-Aware",
    r1_desc: "IA multimodale che risponde a query complesse 24/7.",
    r2_title: "Rete Neurale Supply Chain",
    r2_desc: "ML predittivo per ordini basati sui trend.",
    r3_title: "Motore di Profitto Dinamico",
    r3_desc: "Elasticità dei prezzi in tempo reale.",
    r4_title: "Griglia Difesa Abbandono",
    r4_desc: "Previsione abbandono VIP.",
    r5_title: "Scoperta Visiva",
    r5_desc: "Ricerca inventario basata su foto.",
    real_estate_name: "Autonomia PropTech",
    real_estate_desc: "Immobiliare",
    re1_title: "Pilota Automatico Lead-to-Close",
    re1_desc: "Agente vocale IA qualifica lead.",
    re2_title: "Valutazione Predittiva",
    re2_desc: "Algoritmo Black-box per stime istantanee.",
    re3_title: "OS Gestione Asset",
    re3_desc: "Invio automatico appaltatori.",
    re4_title: "Staging Generativo",
    re4_desc: "IA converte stanze vuote.",
    re5_title: "Previsore Rendimento",
    re5_desc: "Previsione ROI affitti.",
    b2b_name: "OS Agenzia",
    b2b_desc: "B2B",
    b1_title: "Fonderia Sviluppo Ombra",
    b1_desc: "SDLC White-label per agenzie.",
    b2_title: "Nucleo Contenuto Programmatico",
    b2_desc: "Generazione 500+ articoli SEO.",
    b3_title: "Fabbrica Creativa Ad",
    b3_desc: "GenAI crea 100+ varianti ad.",
    b4_title: "Warehouse Dati Cross-Channel",
    b4_desc: "Unificazione dati dashboard C-Suite.",
    b5_title: "Intelligence Vendite",
    b5_desc: "Monitoraggio segnali finanziamento.",
    corporate_name: "Rete Neurale Enterprise",
    corporate_desc: "Corporate",
    c1_title: "Tessuto Riconciliazione Finanziaria",
    c1_desc: "Sciame multi-agente per fatture.",
    c2_title: "Difesa Legale Cognitiva",
    c2_desc: "LLM privato revisione contratti.",
    c3_title: "Hub Intelligence Conoscenza",
    c3_desc: "DB vettoriale indicizza chiamate/docs.",
    c4_title: "Orchestrazione Workflow",
    c4_desc: "Onboarding dipendenti autonomo.",
    c5_title: "Ottimizzatore Logistica",
    c5_desc: "Ristradamento flotta dinamico.",
    health_name: "OS Operazioni Cliniche",
    health_desc: "Sanità",
    h1_title: "Riattivazione Pazienti",
    h1_desc: "Prenotazione auto pazienti inattivi.",
    h2_title: "Aggiudicazione Assicurativa",
    h2_desc: "Bot RPA verifica idoneità.",
    h3_title: "Monitoraggio Post-Op",
    h3_desc: "Agente vocale controlla recupero.",
    h4_title: "Pilota Automatico Reputazione",
    h4_desc: "Richieste recensioni via sentiment.",
    h5_title: "Comando Vocale Zero-Attesa",
    h5_desc: "IA risponde telefoni e integra EMR.",
    ali_role: "Direttore Strategico",
    ali_arch: "La Governance",
    ali_desc: "Capitale, Rischio, Conformità e Strutturazione Globale.",
    bilal_role: "Capo Ingegneria",
    bilal_arch: "Il Motore",
    bilal_desc: "Architettura Agentica ed Esecuzione Deep Tech.",
  },
  de: {
    nav: { philosophy: "Philosophie", systems: "Systeme", leadership: "Führung", deploy: "Bereitstellen", home: "Start" },
    hero: {
      tagline: "Souveräne Intelligenz",
      headline: "Autonome Infrastruktur.\nGlobale Autorität.",
      subheadline: "Wir entwickeln hochmargige automatisierte Ökosysteme. Brückenschlag zwischen westlicher Unternehmensnachfrage und Mailänder Designpräzision.",
      cta: "Infrastruktur Bereitstellen",
      caseStudies: "Fallstudien Ansehen",
      stat1Label: "Totale Automatisierung",
      stat1Value: "99.9%",
      stat2Label: "Kostenreduktion",
      stat2Value: "€3.9M/Jahr",
      loc1: "GLOBALER SITZ",
      loc2: "INNOVATIONS-HUB",
    },
    philosophy: {
      title: "Das Souveräne Modell",
      subtitle: "Eine Dual-Node-Architektur für Geschwindigkeit, Sicherheit und absolute Skalierung.",
      card1Title: "Governance-Kern",
      card1Subtitle: "COMPLIANCE & RISIKO",
      card1Desc: "Das Fundament unserer Operation. Wir halten uns an G20-Compliance-Standards und ACCA-Finanzkontrollen.",
      card2Title: "Neurale Gießerei",
      card2Subtitle: "DEEP TECH AUSFÜHRUNG",
      card2Desc: "Der Motor der Schöpfung. Heimat unserer Agentic AI Swarms in Mailand. Wir umgehen bürokratische Verlangsamungen.",
      processTitle: "Bereitstellungsprotokoll",
      step1: "Audit & Architektur",
      step2: "Schwarm-Bereitstellung",
      step3: "Autonome Skalierung",
    },
    systems: {
      title: "Die Lösungsmatrix",
      subtitle: "25 Spezialisierte Systeme. Organisiert für sofortige Wirkung.",
    },
    leadership: {
      title: "Die Architekten",
      subtitle: "Die Schnittstelle von Strategischer Governance und Neural Engineering.",
    },
    footer: {
      basedIn: "Global Operierend.",
      rights: "Alle Souveränen Rechte Vorbehalten.",
      request: "Zugang Anfordern"
    },
     // Fallback English for dynamic items in demo
    retail_name: "Kognitiver Handel",
    retail_desc: "Einzelhandel",
    r1_title: "Omni-Aware Verkaufs-Concierge",
    r1_desc: "Multimodale KI beantwortet komplexe Fragen 24/7.",
    r2_title: "Lieferketten-Neuronales Netzwerk",
    r2_desc: "Prädiktives ML passt Bestellungen an.",
    r3_title: "Dynamischer Gewinnmotor",
    r3_desc: "Echtzeit-Preiselastizität.",
    r4_title: "Abwanderungs-Verteidigungsnetz",
    r4_desc: "Vorhersage von VIP-Abwanderung.",
    r5_title: "Visuelle Entdeckung",
    r5_desc: "Vektorbasierte Inventarsuche.",
    real_estate_name: "PropTech Autonomie",
    real_estate_desc: "Immobilien",
    re1_title: "Lead-to-Close Autopilot",
    re1_desc: "KI-Sprachagent qualifiziert Leads.",
    re2_title: "Prädiktive Bewertung",
    re2_desc: "Black-Box-Algo für Sofortbewertung.",
    re3_title: "Asset Management OS",
    re3_desc: "Automatische Beauftragung von Auftragnehmern.",
    re4_title: "Generatives Staging",
    re4_desc: "KI verwandelt leere Räume.",
    re5_title: "Ertragsprognose",
    re5_desc: "ROI-Vorhersage.",
    b2b_name: "Agentur-Betriebssystem",
    b2b_desc: "B2B",
    b1_title: "Schatten-Entwicklungs-Gießerei",
    b1_desc: "White-Label SDLC für Agenturen.",
    b2_title: "Programmatischer Inhaltskern",
    b2_desc: "Generierung von 500+ SEO-Artikeln.",
    b3_title: "Anzeigen-Kreativ-Fabrik",
    b3_desc: "GenAI erstellt 100+ Anzeigenvarianten.",
    b4_title: "Cross-Channel Data Warehouse",
    b4_desc: "Vereinheitlichung von Daten.",
    b5_title: "Vertriebsintelligenz",
    b5_desc: "Überwachung von Finanzierungssignalen.",
    corporate_name: "Unternehmens-Neuronales Netzwerk",
    corporate_desc: "Konzern",
    c1_title: "Finanzabgleichsgewebe",
    c1_desc: "Multi-Agenten-Schwarm für Rechnungen.",
    c2_title: "Kognitive Rechtsverteidigung",
    c2_desc: "Private LLM prüft Verträge.",
    c3_title: "Wissensintelligenz-Hub",
    c3_desc: "Vektor-DB indiziert Anrufe/Doks.",
    c4_title: "Workflow-Orchestrierung",
    c4_desc: "Autonomes Mitarbeiter-Onboarding.",
    c5_title: "Logistik-Optimierer",
    c5_desc: "Dynamische Flottenumleitung.",
    health_name: "Klinisches Betriebs-OS",
    health_desc: "Gesundheitswesen",
    h1_title: "Patientenreaktivierung",
    h1_desc: "Automatische Buchung inaktiver Patienten.",
    h2_title: "Versicherungsentscheidung",
    h2_desc: "RPA-Bot prüft Berechtigung.",
    h3_title: "Post-Op Überwachung",
    h3_desc: "Sprachagent prüft Erholung.",
    h4_title: "Reputations-Autopilot",
    h4_desc: "Stimmungsgesteuerte Bewertungsanfragen.",
    h5_title: "Null-Wartezeit Sprachbefehl",
    h5_desc: "KI beantwortet Telefone.",
    ali_role: "Strategischer Direktor",
    ali_arch: "Die Governance",
    ali_desc: "Kapital, Risiko, Compliance und globale Strukturierung.",
    bilal_role: "Leiter Technik",
    bilal_arch: "Der Motor",
    bilal_desc: "Agentic Architecture und Deep Tech Execution.",
  }
};

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: 'retail',
    nameKey: 'retail_name',
    descriptionKey: 'retail_desc',
    promptContext: 'Futuristic warehouse with flying drones and data overlays',
    items: [
      { id: 'r1', titleKey: 'r1_title', descriptionKey: 'r1_desc', span: 'md:col-span-2' },
      { id: 'r2', titleKey: 'r2_title', descriptionKey: 'r2_desc' },
      { id: 'r3', titleKey: 'r3_title', descriptionKey: 'r3_desc' },
      { id: 'r4', titleKey: 'r4_title', descriptionKey: 'r4_desc' },
      { id: 'r5', titleKey: 'r5_title', descriptionKey: 'r5_desc' },
    ]
  },
  {
    id: 'real-estate',
    nameKey: 'real_estate_name',
    descriptionKey: 'real_estate_desc',
    promptContext: 'Luxury London penthouse at night with digital holographic price tags',
    items: [
      { id: 're1', titleKey: 're1_title', descriptionKey: 're1_desc', span: 'md:col-span-2' },
      { id: 're2', titleKey: 're2_title', descriptionKey: 're2_desc' },
      { id: 're3', titleKey: 're3_title', descriptionKey: 're3_desc' },
      { id: 're4', titleKey: 're4_title', descriptionKey: 're4_desc' },
      { id: 're5', titleKey: 're5_title', descriptionKey: 're5_desc' },
    ]
  },
  {
    id: 'b2b',
    nameKey: 'b2b_name',
    descriptionKey: 'b2b_desc',
    promptContext: 'Abstract digital marketing dashboard glowing in void black',
    items: [
      { id: 'b1', titleKey: 'b1_title', descriptionKey: 'b1_desc', span: 'md:col-span-2' },
      { id: 'b2', titleKey: 'b2_title', descriptionKey: 'b2_desc' },
      { id: 'b3', titleKey: 'b3_title', descriptionKey: 'b3_desc' },
      { id: 'b4', titleKey: 'b4_title', descriptionKey: 'b4_desc' },
      { id: 'b5', titleKey: 'b5_title', descriptionKey: 'b5_desc' },
    ]
  },
  {
    id: 'corporate',
    nameKey: 'corporate_name',
    descriptionKey: 'corporate_desc',
    promptContext: 'Futuristic server room with blue data streams and glass walls',
    items: [
      { id: 'c1', titleKey: 'c1_title', descriptionKey: 'c1_desc', span: 'md:col-span-2' },
      { id: 'c2', titleKey: 'c2_title', descriptionKey: 'c2_desc' },
      { id: 'c3', titleKey: 'c3_title', descriptionKey: 'c3_desc' },
      { id: 'c4', titleKey: 'c4_title', descriptionKey: 'c4_desc' },
      { id: 'c5', titleKey: 'c5_title', descriptionKey: 'c5_desc' },
    ]
  },
  {
    id: 'health',
    nameKey: 'health_name',
    descriptionKey: 'health_desc',
    promptContext: 'High-tech pristine medical interface with DNA sequencing visuals',
    items: [
      { id: 'h1', titleKey: 'h1_title', descriptionKey: 'h1_desc', span: 'md:col-span-2' },
      { id: 'h2', titleKey: 'h2_title', descriptionKey: 'h2_desc' },
      { id: 'h3', titleKey: 'h3_title', descriptionKey: 'h3_desc' },
      { id: 'h4', titleKey: 'h4_title', descriptionKey: 'h4_desc' },
      { id: 'h5', titleKey: 'h5_title', descriptionKey: 'h5_desc' },
    ]
  }
];

export const LEADERS: Leader[] = [
  {
    id: "ali",
    name: "Ali",
    roleKey: "ali_role",
    archetypeKey: "ali_arch",
    descriptionKey: "ali_desc",
    imagePrompt: "Portrait of a serious strategic arab businessman in futuristic suit, dark cinematic lighting"
  },
  {
    id: "bilal",
    name: "Bilal",
    roleKey: "bilal_role",
    archetypeKey: "bilal_arch",
    descriptionKey: "bilal_desc",
    imagePrompt: "Portrait of a visionary tech leader south asian, minimalist backdrop, cyberpunk aesthetics"
  }
];